# Generated by Django 4.1.3 on 2022-11-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_age_contact_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Age',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
