# Generated by Django 4.1.3 on 2022-11-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_contact_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
